export type Collection = 'all' | 'current' | 'classic' | 'popular' | 'pro' | 'flagship';
export type Component = {
  id: string;
  name: string;
  english: string;
  title: string;
  description: string;
  specs: [string, string][];
  x: number;
  y: number;
  catalogIds?: string[];
};
export type Paint = {
  id: string;
  name: string;
  hex: string;
  image: string;
  source: string;
  imageRatio: number;
  imagePosition?: string;
  imageTone?: 'dark';
  note?: string;
  hotspots?: Record<string, { x: number; y: number }>;
};
export type Brand = { id: string; name: string; country: string; founded: string };
export type GeometrySize = {
  size: string;
  stack: number;
  reach: number;
  headAngle: number;
  seatAngle: number;
  wheelbase: number | null;
  chainstay: number;
  bbDrop: number;
  headTube: number;
  seatTube?: number;
};
export type Bike = {
  id: string;
  brandId: string;
  name: string;
  family: string;
  build: string;
  edition: string;
  kind: string;
  description: string;
  collections: Collection[];
  image: string;
  imageCredit: string;
  imageNote?: string;
  imageRatio: number;
  imageSource?: string;
  imageTone?: 'dark';
  imagePosition?: string;
  color: string;
  colorHex: string;
  paints?: Paint[];
  race?: { label: string; note: string; source: string };
  price?: { label: string; market: string; source: string; checkedAt: string };
  source: string;
  sourceLabel: string;
  checkedAt: string;
  weight: string;
  weightLabel?: string;
  weightNote: string;
  groupset: string;
  hasPowerMeter: boolean;
  material: string;
  components: Component[];
  geometry: {
    status?: 'unavailable';
    sizes: GeometrySize[];
    defaultSize: string;
    source: string;
    sourceLabel: string;
    note: string;
  };
  aero: { title: string; description: string; source: string; limit: string };
};
export type Catalog = { updatedAt: string; brands: Brand[]; bikes: Bike[]; collectionNote: string };

export type PartCategory =
  'wheels' | 'groupsets' | 'tires' | 'handlebars' | 'seatposts' | 'saddles';
export type Product = {
  id: string;
  brandId: string;
  name: string;
  category: PartCategory;
  era: string;
  status: 'current' | 'classic';
  tagline: string;
  description: string;
  image?: string;
  imageCaption?: string;
  imageSource?: string;
  specs: [string, string][];
  highlights: { title: string; text: string }[];
  compatibility: string;
  tradeoff: string;
  source: string;
  sourceLabel: string;
  checkedAt: string;
};
export type PartsCatalog = {
  updatedAt: string;
  brands: (Brand & { description: string; website: string })[];
  products: Product[];
};
