export type Collection = 'all' | 'current' | 'classic' | 'popular';
export type Component = {
  id: string;
  name: string;
  english: string;
  title: string;
  description: string;
  specs: [string, string][];
  x: number;
  y: number;
};
export type Brand = { id: string; name: string; country: string; founded: string };
export type GeometrySize = {
  size: string;
  stack: number;
  reach: number;
  headAngle: number;
  seatAngle: number;
  wheelbase: number | null;
  chainstay: number;
  bbDrop: number;
  headTube: number;
  seatTube?: number;
};
export type Bike = {
  id: string;
  brandId: string;
  name: string;
  family: string;
  build: string;
  edition: string;
  kind: string;
  description: string;
  collections: Collection[];
  image: string;
  imageCredit: string;
  imageNote?: string;
  imageRatio: number;
  imageSource?: string;
  imageTone?: 'dark';
  imagePosition?: string;
  color: string;
  colorHex: string;
  source: string;
  sourceLabel: string;
  checkedAt: string;
  weight: string;
  weightNote: string;
  groupset: string;
  material: string;
  components: Component[];
  geometry: {
    sizes: GeometrySize[];
    defaultSize: string;
    source: string;
    sourceLabel: string;
    note: string;
  };
  aero: { title: string; description: string; source: string; limit: string };
};
export type Catalog = { updatedAt: string; brands: Brand[]; bikes: Bike[]; collectionNote: string };
